### ISSUE TITLE
Cannot read property 'table' of undefined

### ISSUE THREAD

**Issue by Suvitruf** [hden/rethinkdb-pool#14]
var r    = require('rethinkdb');
     var Pool = require('rethinkdb-pool');

     var pool = Pool({
         host:rHost,
         port:rPort,
         db:'Unnyworld',
         r: r
     });

But when trying to make query:

     var addPlayer = pool.r.table(TABLE_PLAYERS).insert(player, {conflict: "replace"});

got error:

     var addPlayer = pool.r.table(TABLE_PLAYERS).insert(player, {conflict: 
                           ^
     TypeError: Cannot read property 'table' of undefined

**Comment by hden** [comment]
@Suvitruf In short you can just use `r = require('rethindb')` as long as it's passed into `Pool` as well.
