### ISSUE TITLE
Update generic-pool dependency

### ISSUE THREAD

**Issue by Zacaria** [hden/rethinkdb-pool#18]
Hi, I really appreciated your work.

Do you think it is possible to update your generic-pool dependency ?

There is a migration guide [here](https://gist.github.com/sandfox/5ca20648b60a0cb959638c0cd6fcd02d)

If you don't have time now, I would be glad to do it myself and drop you a PR. I may be able to do the PR in one or two weeks.

And happy new year ! :tada:

**Comment by hden** [comment]
@Zacaria I've created a pull request for this. Would you kindly review it for me?
