### ISSUE TITLE
Example with middleware?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [hden/rethinkdb-pool#21]
Can we see an example with middleware? Specifically, I'm not sure how to best release resources with Express middleware, since most routes finish their work and don't call next() to continue more middleware.

**Comment by hden** [comment]
It's probably easier to write a middleware.

```js
const createPool = require('rethinkdb-pool')
const createMiddleware = function (r, options) {
  const pool = createPool(r, options)
  return function (req, res, next) {
    req.run = pool.run
    next()
  }
}

const express = require('express')
const app = express()
app.use(createMiddleware(r, { /* options */ }))

app.get('/', function (req, res) {
  // Resources are automatically released if called via `pool.run()`
  req.run(/* query */).then()
})
```

**Comment by GeoffreyPlitt** [comment]
OK, but I'd have to rewrite hundreds of queries of the form ```query().run(conn)``` to use ```req.run```. There isn't a way to do this with the former syntax? I have a large codebase that already passes around a ```conn``` object, so I'd love to keep it that way.

**Comment by hden** [comment]
AFAIK [koa](http://koajs.com) provides what you want. Since you probably don't want to perform a major refactoring, perhaps you would like to ask around in the express community instead?
