### ISSUE TITLE
Connection errors

### ISSUE THREAD

**Issue by caracal7** [hden/rethinkdb-pool#45]
How to check connection error(wrong host/port/password) on createPool?

**Comment by hden** [comment]
This library is a light wrapper over the generic-pool library. The returned pool object should be an event emitter.

```js
var r = require('rethinkdb')
var createPool = require('rethinkdb-pool')
var pool = createPool(r, {
  host:'localhost',
  port:28015,
  db:'marvel',
  authKey:'hunter2'
})

pool.on('factoryCreateError', function(err){
  //log stuff maybe
})
```

ref: https://github.com/coopernurse/node-pool#poolon

**Comment by caracal7** [comment]
Thanks a lot)
